# Generated by Django 5.1.4 on 2025-03-30 21:24

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalSupply",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "unspsc_code",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UNSPSC编码",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="物资名称")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DG", "药品"),
                            ("DV", "医疗设备"),
                            ("PP", "防护装备"),
                            ("RT", "检测试剂"),
                            ("CS", "一次性耗材"),
                            ("OT", "其他"),
                        ],
                        max_length=2,
                        verbose_name="物资类型",
                    ),
                ),
                ("unit", models.CharField(max_length=10, verbose_name="计量单位")),
                ("standard", models.CharField(max_length=100, verbose_name="执行标准")),
                ("shelf_life", models.PositiveIntegerField(verbose_name="保质期(月)")),
                (
                    "storage_temp",
                    models.CharField(max_length=20, verbose_name="存储温度"),
                ),
                (
                    "is_controlled",
                    models.BooleanField(default=False, verbose_name="受控物资"),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "avg_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="平均价格",
                    ),
                ),
                (
                    "min_stock_level",
                    models.PositiveIntegerField(default=0, verbose_name="最低库存量"),
                ),
            ],
            options={
                "verbose_name": "医疗物资",
            },
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "hospital_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "org_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="机构编码"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="医院名称")),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "社区医院"),
                            (2, "区级医院"),
                            (3, "三甲医院"),
                            (4, "三乙医院"),
                            (5, "二甲医院"),
                            (6, "二乙医院"),
                            (7, "一甲医院"),
                            (8, "一乙医院"),
                            (9, "其他"),
                        ],
                        verbose_name="医院等级",
                    ),
                ),
                ("address", models.TextField(verbose_name="详细地址")),
                (
                    "geo_location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="地理坐标"
                    ),
                ),
                (
                    "contact_info",
                    models.JSONField(default=dict, verbose_name="联系信息"),
                ),
                (
                    "storage_volume",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="仓储容量"
                    ),
                ),
                (
                    "current_capacity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="当前库存"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="所属地区"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
                (
                    "warning_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        help_text="百分比，例如20.00表示当库存低于容量的20%时预警",
                        max_digits=5,
                        verbose_name="库存预警阈值",
                    ),
                ),
            ],
            options={
                "verbose_name": "医疗机构",
                "indexes": [models.Index(fields=["org_code"], name="org_code_idx")],
            },
        ),
        migrations.CreateModel(
            name="InventoryBatch",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "batch_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(max_length=50, unique=True, verbose_name="批次号"),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="库存数量")),
                ("production_date", models.DateField(verbose_name="生产日期")),
                ("expiration_date", models.DateField(verbose_name="失效日期")),
                (
                    "storage_condition",
                    models.JSONField(default=dict, verbose_name="存储条件"),
                ),
                (
                    "received_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="入库日期"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="单价",
                    ),
                ),
                (
                    "quality_check_passed",
                    models.BooleanField(default=True, verbose_name="质检通过"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="api.hospital",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supply",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory",
                        to="api.medicalsupply",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存批次",
            },
        ),
        migrations.CreateModel(
            name="ItemFulfillment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "fulfillment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="分配数量")),
                (
                    "fulfilled_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="履行时间"),
                ),
                (
                    "fulfilled_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inventory_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.inventorybatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "物资分配记录",
            },
        ),
        migrations.CreateModel(
            name="RequestItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "item_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="需求数量")),
                (
                    "allocated",
                    models.PositiveIntegerField(default=0, verbose_name="已分配数量"),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="备注"),
                ),
                (
                    "fulfilled_from_batches",
                    models.ManyToManyField(
                        through="api.ItemFulfillment", to="api.inventorybatch"
                    ),
                ),
                (
                    "supply",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.medicalsupply",
                    ),
                ),
            ],
            options={
                "verbose_name": "请求明细",
            },
        ),
        migrations.AddField(
            model_name="itemfulfillment",
            name="request_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.requestitem"
            ),
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "supplier_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="供应商名称")),
                (
                    "contact_person",
                    models.CharField(max_length=50, verbose_name="联系人"),
                ),
                (
                    "contact_info",
                    models.JSONField(default=dict, verbose_name="联系方式"),
                ),
                ("address", models.TextField(blank=True, verbose_name="地址")),
                (
                    "credit_rating",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="信用评级",
                    ),
                ),
            ],
            options={
                "verbose_name": "供应商",
                "indexes": [models.Index(fields=["name"], name="supplier_name_idx")],
            },
        ),
        migrations.AddField(
            model_name="medicalsupply",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplies",
                to="api.supplier",
            ),
        ),
        migrations.AddField(
            model_name="inventorybatch",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="batches",
                to="api.supplier",
            ),
        ),
        migrations.CreateModel(
            name="SupplyRequest",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "request_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                ("required_by", models.DateTimeField(verbose_name="需求时间")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DF", "草稿"),
                            ("SB", "已提交"),
                            ("AP", "已批准"),
                            ("FL", "已完成"),
                            ("RJ", "已拒绝"),
                            ("CN", "已取消"),
                        ],
                        default="DF",
                        max_length=2,
                        verbose_name="状态",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(default=3, verbose_name="优先级"),
                ),
                (
                    "approval_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审批时间"
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="备注")),
                (
                    "emergency",
                    models.BooleanField(default=False, verbose_name="紧急请求"),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="api.hospital",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "物资请求",
                "ordering": ["-priority", "required_by"],
            },
        ),
        migrations.AddField(
            model_name="requestitem",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="api.supplyrequest",
            ),
        ),
        migrations.CreateModel(
            name="InventoryAlert",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "alert_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("LS", "库存不足"),
                            ("EX", "即将过期"),
                            ("ED", "已过期"),
                            ("CP", "仓储容量预警"),
                        ],
                        max_length=2,
                        verbose_name="预警类型",
                    ),
                ),
                ("message", models.TextField(verbose_name="预警信息")),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="是否解决"),
                ),
                (
                    "resolved_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解决时间"
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="api.hospital",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="api.inventorybatch",
                    ),
                ),
                (
                    "supply",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="api.medicalsupply",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存预警",
                "indexes": [
                    models.Index(fields=["alert_type"], name="alert_type_idx"),
                    models.Index(fields=["is_resolved"], name="alert_resolved_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="itemfulfillment",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="fulfillment_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="medicalsupply",
            constraint=models.UniqueConstraint(
                fields=("name", "category"), name="unique_supply"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorybatch",
            index=models.Index(fields=["expiration_date"], name="expiry_idx"),
        ),
        migrations.AddIndex(
            model_name="inventorybatch",
            index=models.Index(fields=["received_date"], name="received_date_idx"),
        ),
        migrations.AddIndex(
            model_name="inventorybatch",
            index=models.Index(fields=["batch_number"], name="batch_number_idx"),
        ),
        migrations.AddConstraint(
            model_name="requestitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("allocated__lte", models.F("quantity"))),
                name="allocated_le_required",
            ),
        ),
    ]
