# Generated by Django 5.1.4 on 2025-04-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital",
            name="level",
            field=models.IntegerField(
                choices=[
                    (9, "三甲医院"),
                    (8, "三乙医院"),
                    (7, "二甲医院"),
                    (6, "二乙医院"),
                    (5, "一甲医院"),
                    (4, "一乙医院"),
                    (3, "区级医院"),
                    (2, "社区医院"),
                    (1, "其他"),
                ],
                verbose_name="医院等级",
            ),
        ),
    ]
