# Generated by Django 5.1.4 on 2025-04-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_hospital_level"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="requestitem",
            options={
                "ordering": ["-priority", "request__required_by"],
                "verbose_name": "请求明细",
            },
        ),
        migrations.AddField(
            model_name="requestitem",
            name="priority",
            field=models.FloatField(default=0.5, verbose_name="优先得分"),
        ),
        migrations.AlterField(
            model_name="supplyrequest",
            name="priority",
            field=models.FloatField(default=0.5, verbose_name="优先得分"),
        ),
    ]
